apiVersion: v1
kind: Service
metadata:
  name: udp-measure
spec:
  selector:
    app: udp-measure
  type: NodePort
  ports:
    - protocol: UDP
      port: 12345
      targetPort: 12345
      nodePort: 31234
