apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Chart.Name }}
spec:
  type: {{.Values.serviceType}}
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: {{.Values.nodePort}}
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector}}
      containers:
        - name: {{ .Chart.Name }}
          image: registry.gitlab.com/haorui/docker_images/tcp-server
          ports:
          - containerPort: 5000
      imagePullSecrets:
        - name: gitlab-auth
